docs: update badges and clean
okp4/template-kafka-processor pull request #37
Opened 2022-09-22 12:26 UTC by hleonardtek

Self explanatory.

2022-09-22 14:53 UTC, amimart approved these changes

2022-09-23 06:42 UTC, ad2ien requested changes
Can we add the contributing section ?
Thx!

2022-09-23 07:37 UTC, ccamel approved these changes

2022-09-23 11:50 UTC, amimart approved these changes

2022-09-23 12:43 UTC, ad2ien approved these changes

2022-09-23 12:52 UTC, merged